name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t local-webpage .

    - name: Run Docker container
      run: |
        docker run -d -p 80:80 --name webpage local-webpage
        sleep 5  # Aguarda alguns segundos para garantir que o servidor está rodando

    - name: Check if Nginx is running
      run: |
        docker exec webpage nginx -t
        docker exec webpage curl -f http://localhost/
